#!/usr/bin/env bash
# Keep the generated pieces of the image naming rule in sync:
#   * graphql's pkg/imageref/imageref.go copied into the install-app and
#     install-agent modules (separate, stdlib-only Go modules: they cannot import it)
#   * the list of images that have a frozen copy (deploy/images.txt "mirror"
#     rows, minus optional ones) as Go (pkg/imageref/mirrored.go, also copied)
#     and Helm (deploy/helm/ace/templates/_mirrored.tpl). With IMAGE_REGISTRY
#     empty only these are renamed to agentcert/<flat name>; any other image
#     (user charts, custom experiment images) keeps its upstream name.
# Run after editing pkg/imageref/imageref.go or deploy/images.txt;
# scripts/tests/test-registry-tooling.sh fails when anything is out of date.
#   ./scripts/lib/sync-imageref.sh           write the files
#   ./scripts/lib/sync-imageref.sh --check   exit 1 if a file differs
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PKG="${REPO_ROOT}/AgentCert/chaoscenter/graphql/server/pkg/imageref"
# shellcheck source=registry.sh
source "${REPO_ROOT}/scripts/lib/registry.sh"

mirrored_refs() {
    inventory_rows "${REPO_ROOT}/deploy/images.txt" mirror | cut -d'|' -f3 \
        | while read -r i; do image_canonical "$i"; echo; done | sort -u
}
render_copy() {
    printf '// Code generated by scripts/lib/sync-imageref.sh from\n'
    printf '// AgentCert/chaoscenter/graphql/server/pkg/imageref/imageref.go. DO NOT EDIT.\n\n'
    sed -e 's/^package imageref$/package main/' "${PKG}/imageref.go"
}
render_mirrored_go() {
    local pkg="$1"
    printf '// Code generated by scripts/lib/sync-imageref.sh from deploy/images.txt. DO NOT EDIT.\n\n'
    printf 'package %s\n\n' "${pkg}"
    printf '// mirroredImages are the upstream images that have a frozen copy under\n'
    printf '// IMAGE_MIRROR_NAMESPACE on Docker Hub (deploy/images.txt "mirror" rows).\n'
    printf 'var mirroredImages = func() map[string]bool {\n'
    printf '\tm := map[string]bool{}\n'
    printf '\tfor _, ref := range []string{\n'
    mirrored_refs | while read -r r; do printf '\t\t"%s",\n' "${r}"; done
    printf '\t} {\n\t\tm[ref] = true\n\t}\n\treturn m\n}()\n'
}
render_mirrored_tpl() {
    printf '{{/* Code generated by scripts/lib/sync-imageref.sh from deploy/images.txt. DO NOT EDIT.\n'
    printf '     Upstream images with a frozen copy under imageMirrorNamespace (see ace.image). */}}\n'
    printf '{{- define "ace.mirroredImages" -}}\n'
    mirrored_refs | python3 -c 'import json,sys; print(json.dumps([l.strip() for l in sys.stdin if l.strip()]))'
    printf '{{- end -}}\n'
}

declare -A TARGETS=(
    ["${REPO_ROOT}/app-charts/install-app/imageref.go"]="render_copy"
    ["${REPO_ROOT}/agent-charts/install-agent/imageref.go"]="render_copy"
    ["${PKG}/mirrored.go"]="render_mirrored_go imageref"
    ["${REPO_ROOT}/app-charts/install-app/mirrored.go"]="render_mirrored_go main"
    ["${REPO_ROOT}/agent-charts/install-agent/mirrored.go"]="render_mirrored_go main"
    ["${REPO_ROOT}/deploy/helm/ace/templates/_mirrored.tpl"]="render_mirrored_tpl"
)
rc=0
for dst in "${!TARGETS[@]}"; do
    # shellcheck disable=SC2086  # the value is "function [arg]"
    if [[ "${1:-}" == --check ]]; then
        if ! diff -q <(${TARGETS[${dst}]}) "${dst}" >/dev/null 2>&1; then
            echo "out of date: ${dst#"${REPO_ROOT}/"} (run scripts/lib/sync-imageref.sh)" >&2
            rc=1
        fi
    else
        ${TARGETS[${dst}]} > "${dst}"
        echo "wrote ${dst#"${REPO_ROOT}/"}"
    fi
done
exit "${rc}"
